version: '3'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  api:
    container_name: api
    build: ./
    links:
      - redis
    ports:
      - 5000:5000
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=production
      - PORT=5000
    command: yarn run start
